### ISSUE TITLE
주제 정하기

### ISSUE THREAD

**Issue by JeonYeBeen** [21800430/team-mini_project#1]

**Comment by JeonYeBeen** [comment]
저희 주제는 어떤 걸로 할까요?

**Comment by 21800430** [comment]
저는 식당이나 매점, 서점을 생각해 봤어요.
각각 음식, 식료품, 서적 등을 다루는 걸로 하려는데 어떤게 좋으세요?

**Comment by JeonYeBeen** [comment]
서점 괜찮은 거 같아요!

**Comment by 21800430** [comment]
네 그러면 서점으로 해봐요!
서적 분류는 어떻게 해볼까요?

**Comment by JeonYeBeen** [comment]
항목은 제목, 가격, 장르, 저자, 출판사, 별점이 좋을 거 같아요

**Comment by 21800430** [comment]
네 그리고 품절여부 등은 어떨까요?
사람들이 구매할 때 어려움이 없도록 하면 좋을 것 같아요.

**Comment by JeonYeBeen** [comment]
품절여부도 좋습니다!

**Comment by 21800430** [comment]
아 품절여부만 있으면 좀 애매할 수도 있으니 재고량으로 해봐요!
9권 이하만 표시하고 10권 이상은 9+이렇게 표시하는 걸로

**Comment by 21800430** [comment]
아니면 숫자대신 '품절', '품절임박'같이 표현하는 방법도 있어요

**Comment by JeonYeBeen** [comment]
그러면 그 부부은 함수를 사용해서 나타내도 괜찮을 거 같아요.
2권 이하로 남았으면은 품절임박으로 나타나도록

**Comment by 21800430** [comment]
네 그럼 재고량과 품절여부 부분은 일단은 초기값만 넣는 것으로 할까요?
이 부분을 다루려면 구매 부분 코드를 새로 만들어야 해서 지금은 아직 힘들 것 같아요.

**Comment by JeonYeBeen** [comment]
네 좋아요

**Comment by JeonYeBeen** [comment]
그러면 주제는 이만할까요?

**Comment by 21800430** [comment]
네 그래요.

**Comment by JeonYeBeen** [comment]
다른 issue 만들도록 하겠습니다
