### ISSUE TITLE
역할 분담

### ISSUE THREAD

**Issue by JeonYeBeen** [21800430/team-mini_project#2]
역할 분담은 어떻게 할까요?

**Comment by 21800430** [comment]
우선 저희가 할 일이 코딩, 위키, 블로그 등이 있는데, 코딩은 메인이라서 같이 하고 위키랑 블로그를 각자 나눠야 할 것 같은데 어느 쪽이 좋으세요?

**Comment by JeonYeBeen** [comment]
제가 위키를 작성하겠습니다

**Comment by 21800430** [comment]
네 그러면 제가 블로그를 만들게요

**Comment by JeonYeBeen** [comment]
코딩은 두 부분으로 나눌게요!
1. C, U, 검색기능
2. R, D, 파일 저장, 읽기

**Comment by JeonYeBeen** [comment]
몇 번 하실래요?

**Comment by 21800430** [comment]
저는 2번으로 할게요

**Comment by JeonYeBeen** [comment]
21800645 : 위키정리, 코딩 1.
21800430 : 블로그 정리(README), 코딩 2

**Comment by JeonYeBeen** [comment]
아 메인은 어떻게 할까요?

**Comment by 21800430** [comment]
메인은 만들어놓은게 있으니 제가 할게요

**Comment by JeonYeBeen** [comment]
아 네 감사합니다!

**Comment by 21800430** [comment]
그럼 각자 맡은 부분 내일까지 만들어와요!

**Comment by 21800430** [comment]
이만 대화 닫겠습니다!

**Comment by JeonYeBeen** [comment]
네!
