### ISSUE TITLE
struct Book의 멤버

### ISSUE THREAD

**Issue by JeonYeBeen** [21800430/team-mini_project#3]
b.no 를 사용하셨는데, 이건 도서 번호를 말씀하시는 건가요?

**Comment by 21800430** [comment]
네 도서 지정을 할 때 가장 간단한게 번호 붙여서 고르는거라서 넣었는데 제목으로 변경하는게 더 나을까요?

**Comment by JeonYeBeen** [comment]
아니면 번호는 따로 적어주는 것은 어떨까요?

**Comment by 21800430** [comment]
번호를 따로 적는다는게 구체적으로 어떤 의미인가요?

**Comment by JeonYeBeen** [comment]
파라미터로 인덱스로 넘겨주는 것이여

**Comment by 21800430** [comment]
인덱스를 넣으면 수정이나 삭제할 때 사용할 수 없는데 괜찮나요?

**Comment by JeonYeBeen** [comment]
아 그러면 번호을 넣는게 좋을 거 같네요!
