### ISSUE TITLE
addBook과 updateBook의 항목 입력

### ISSUE THREAD

**Issue by 21800430** [21800430/team-mini_project#4]
addBook과 updateBook에서 번호를 입력하라는 코드가 있는데 그냥 인덱스 순서대로 번호를 넣는것이 더 좋지 않을까요?

**Comment by JeonYeBeen** [comment]
네, 그렇게 하죠!
처음에 번호를 도서 고유 번호로 말씀하신 줄 알아서 그렇게 했어요

**Comment by 21800430** [comment]
저도 당연하게 넘어갔었는데 나중에 보니 설명이 부족했더라고요.
다음엔 정확하게 말할게요
